# Generated by Django 3.2.16 on 2023-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client/image/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='client/resume/'),
        ),
    ]
